# Generated by Django 3.2.9 on 2021-11-14 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_category_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_todo_set', to='noter.category'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_todo_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
