# Generated by Django 3.2.9 on 2021-11-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noter', '0002_auto_20211114_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
