# Generated by Django 3.2.9 on 2021-11-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noter', '0005_auto_20211117_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dueDate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='dueTime',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
