# Generated by Django 3.2.9 on 2021-11-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noter', '0007_category_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uuid',
        ),
    ]
